features/portalAdmin/DARTS_Admin_Courthouse.feature
https://tools.hmcts.net/jira/browse/DMP-4710
- Guildford courts have changed location from London to South East
=> DMP-4710 Amending admin portal courthouse feature

features/SoapApi/DARTS_AddCase.feature, features/SoapApi/DARTS_AddCourtlog.feature, features/SoapApi/DARTS_DailyList.feature, features/SoapApi/DARTS_Events.feature, src/support/data-table.ts
https://tools.hmcts.net/jira/browse/DMP-3945
=> DMP-3945 Adding scenarios for case numbers including whitespace

features/portal/DARTS_Case_Search.feature
N/A
- search was not returning enough results for pagination to be checked
- this was due to the old automation suite running and creating cases
- now it's not running we can use 1 weeks worth of data to get the correct number of results
=> Fixing "Case Search: Search Results Pagination" scenario

features/portalAdmin/DARTS_Admin_Search.feature
See [DMP-4180](https://tools.hmcts.net/jira/browse/DMP-4180)
- Coverage added for DMP-4180.
- Additionally, coverage added for DMP-3307, DMP-3214, DMP-3226 and DMP-3642. These tickets tie together well and are in close proximity to each other.
Tests ran locally and all passed.
=> Scenarios created for case and hearing details

features/SoapApi/DARTS_NewCaseUpdCase.feature
https://tools.hmcts.net/jira/browse/DMP-4752
https://tools.hmcts.net/jira/browse/DMP-4753
=> DMP-4752 DMP-4753 Adding feature for NEWCASE and UPDCASE events

features/JsonApi/DARTS_Cases_API.feature, features/portal/DARTS_Case_Search.feature, src/steps/darts/json.steps.ts
https://tools.hmcts.net/jira/browse/DMP-4748 - courtroom exact match
https://tools.hmcts.net/jira/browse/DMP-4753 - amended addCase API endpoint
Fixes for the latest regression failures:
Fixing add case API endpoint
- it was changed to be `/cases/addCase`
Changes to fix case search changes
- courtroom is now an exact match
=> DMP-4748 DMP-4753 Fixes

features/portalAdmin/DARTS_Admin.feature, features/portalAdmin/DARTS_Admin_Search.feature, features/portalAdmin/DARTS_Admin_Transformed_Media.feature, src/page-objects/base.ts, src/steps/darts/portal.steps.ts
N/A
- no regressions found, just changes to tests required
=> Fixing various scenarios broken by recent code changes

features/portalAdmin/DARTS_Admin_Transcripts.feature
N/A
- removing Requested -> Closed tests as it's not possible anymore
=> Admin transcripts fix

features/SoapApi/DARTS_AddCourtlog.feature, features/endtoend/DARTS_End_to_End_AdvanceSearch.feature, features/portalAdmin/DARTS_Admin_Groups.feature, src/page-objects/base.ts, src/steps/darts/database.steps.ts, src/support/config.ts, src/support/substitution.ts
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
- timezone issue on add court log tests
- fix for time to load groups when creating a group
- advanced search fix for selecting courthouse before they are loaded
=> Fixing latest issues

features/portal/DARTS_Portal.feature, features/portalAdmin/DARTS_Admin.feature, features/portalAdmin/DARTS_Admin_Search.feature, features/portalAdmin/DARTS_Admin_Transcripts.feature
N/A
- changing admin portal transcripts navigation from "Completed transcripts" to "Transcript documents"
- changing admin portal transcripts "Assigned to" to "Last actioned by"
- updating admin search due to recently implemented restrictions
=> Updates to tests

features/SoapApi/DARTS_AddCase.feature, features/SoapApi/DARTS_AddCourtlog.feature, features/SoapApi/DARTS_DailyList.feature, features/SoapApi/DARTS_Events.feature, features/SoapApi/DARTS_GetCases.feature, features/SoapApi/DARTS_RegisterNode.feature
https://tools.hmcts.net/jira/browse/DMP-4794
=> DMP-4794 Removing disabled tag usage

features/portalAdmin/DARTS_Admin_Transformed_Media.feature
https://tools.hmcts.net/jira/browse/DMP-4178
- narrow down search to prevent unwanted results
=> DMP-4178 Minor fix for delete transformed media scenario

features/SoapApi/DARTS_AddCase.feature
https://tools.hmcts.net/jira/browse/DMP-4272
=> DMP-4272 Adding test to trigger defendant name overflow

features/endtoend/DARTS_End_to_End_Judge.feature, features/portal/DARTS_Annotation.feature, src/page-objects/base.ts, src/steps/darts/portal.steps.ts
N/A
Not sure why it's started failing right now, but using an exact name match for the button works.
=> Fixing upload button

Jenkinsfile_CNP, Jenkinsfile_nightly, README.md, features/portalAdmin/DARTS_Admin_Search.feature
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
- for specifying which tags to run
- fixing a failing test
=> Adding pipeline parameters

features/portalAdmin/DARTS_Admin_Search.feature
https://tools.hmcts.net/jira/browse/DMP-4965
- clicking the link on a Case ID no longer navigates to the hearing screen
- updating to click the hearing date link
=> DMP-4965 Admin search hearing results fix

features/portalAdmin/DARTS_Admin_Search.feature
https://tools.hmcts.net/jira/browse/DMP-5054
Fixes for the change in admin search results order
=> DMP-5054 Fixing admin hearing search results order

features/endtoend/DARTS_End_to_End_Requester.feature, features/portalAdmin/DARTS_Admin_Courthouse.feature
https://tools.hmcts.net/jira/browse/DMP-5033
- fixes for DMP-5033 which clears the audio request details after ordering
- `hmcts_staff_2` group has been removed from the Harrow Crown Court courthouse - this was to reduce some email notifications
=> Latest fixes

Jenkinsfile_CNP
Added Jenkins params for API, PORTAL, GATEWAY and test harness URLs
=> Added jenkins config

features/portalAdmin/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-4238
- fixing up and adding `@regression` tag to admin audio deletion scenario
- deleting duplicate scenario for admin deleting audio
- deleting scenarios for checking admin/user portal links
- these were not run and provide little value as the navigation bars are single components that are re-used across all pages
=> DMP-4238 Admin audio deletion scenario

features/portal/DARTS_Language_Shop_User.feature, features/portal/DARTS_Request_Audio.feature, features/portal/DARTS_Super_User.feature, features/portalAdmin/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-5060
To be merged after https://github.com/hmcts/darts-portal/pull/2062
=> DMP-5060 Showing email address on audio request confirmation screen

features/SoapApi/DARTS_AddCase.feature, features/SoapApi/DARTS_AddCourtlog.feature, features/SoapApi/DARTS_DailyList.feature, features/SoapApi/DARTS_Events.feature, features/SoapApi/DARTS_GetCases.feature, features/SoapApi/DARTS_RegisterNode.feature
https://tools.hmcts.net/jira/browse/DMP-5134
- SOAP 404 errors instead of 500
=> Fixes from the release

features/portalAdmin/DARTS_Admin.feature
https://tools.hmcts.net/jira/browse/DMP-4238
=> DMP-4238 Amending hide/delete audio to include banner link click

features/SoapApi/DARTS_TranscriptionEvents.feature, src/steps/darts/api.steps.ts, src/steps/darts/json.steps.ts, src/steps/darts/soap.steps.ts
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
- these were created when there was an issue with some concurrent requests a long time ago
- removing the wait now as it's causing some steps to go over 60s sometimes and timeout
=> Removing delay between sending requests

features/portal/DARTS_Case_Search.feature, features/portalAdmin/DARTS_Admin_Search.feature
32 length check for case number on admin and portal case search
https://tools.hmcts.net/jira/browse/DMP-5144
to be merged after portal [PR](https://github.com/hmcts/darts-portal/pull/2080)
=> Case id validation checks for case search forms

features/portalAdmin/DARTS_Admin.feature, src/page-objects/base.ts
Removed dependency on data creation for admin audio request from DARTS_Request_Audio.feature
Removed disabled "Please select option" from dropdown select
=> Playwright fixes

package.json, yarn.lock
Resolve form-data vulnerability
=> Resolve form-data vulnerability

features/portal/DARTS_Case_Retention.feature, features/portalAdmin/DARTS_Admin_Courthouse.feature, src/page-objects/base.ts
Timeouts for header/link find added, undefined steps resolved
=> Timeouts for header/link find added, undefined steps resolved

features/portalAdmin/DARTS_Admin.feature
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Updated data creation for `DARTS_Admin.feature` to avoid duplicating data in `DARTS_Request_Audio.feature`
=> Admin feature fix
